name: Build and Deploy
on:
  push:
    branches: "main"
jobs:
  demo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: action/chackout@v3
      - name: Install deps
        run: npm ci
      - name: Bulid
        run: npm run build
