name: Node.js CI and Deploy
on:
  push:
    branches: 
        -"main"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to Server
      run: |
          scp -v -r ./dist/* www@109.172.82.155:/home/www/frontend/jenesei.ru/id
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
